@baseURL=http://localhost:3000

##### Create a character :
### route : POST "/characters"
## controller : "CreateCharacter()"
POST {{baseURL}}/characters
Content-Type: application/json

{
    "id": 1,
    "first_name": "Tony",
    "last_name": "Stark",
    "alias": "Iron Man",
    "height": 185
}

##### Create many characters in the same query :
### route : POST "/characters"
## controller : "CreateCharacter()"
POST {{baseURL}}/characters
Content-Type: application/json

[
  {
    "id": 2,
    "first_name": "Steve",
    "last_name": "Rogers",
    "alias": "Captain America",
    "height": 188
  },
  {
    "id": 3,
    "first_name": "Bruce",
    "last_name": "Banner",
    "alias": "The Hulk",
    "height": 175
  },
  {
    "id": 4,
    "first_name": "Thor",
    "last_name": "Odinson",
    "alias": "Thor",
    "height": 198
  },
  {
    "id": 5,
    "first_name": "Natasha",
    "last_name": "Romanoff",
    "alias": "Black Widow",
    "height": 170
  },
  {
    "id": 6,
    "first_name": "Clint",
    "last_name": "Barton",
    "alias": "Hawkeye",
    "height": 188
  },
  {
    "id": 7,
    "first_name": "Peter",
    "last_name": "Parker",
    "alias": "Spider-Man",
    "height": 178
  },
  {
    "id": 8,
    "first_name": "Wanda",
    "last_name": "Maximoff",
    "alias": "Scarlet Witch",
    "height": 170
  },
  {
    "id": 9,
    "first_name": "Vision",
    "last_name": "",
    "alias": "Vision",
    "height": 191
  },
  {
    "id": 10,
    "first_name": "Scott",
    "last_name": "Lang",
    "alias": "Ant-Man",
    "height": 177
  }
]

##### Get all the characters :
### route : GET "/characters"
## controller : "GetAllCharacters()"
GET {{baseURL}}/characters

##### Get a character by id :
### route : GET "/characters/{id}"
## controller : "GetCharacter()"
GET {{baseURL}}/characters/1

##### Update a character by id :
### route : PUT "/characters/{id}"
## controller : "UpdateCharacter()"
PUT {{baseURL}}/characters/1
Content-Type: application/json

{
    "first_name": "Steve",
    "last_name": "Rogers",
    "alias": "Captain America",
    "height": 188
}

##### Delete a character by id :
### route : DELETE "/characters/{id}"
## controller : "DeleteCharacter()"
DELETE {{baseURL}}/characters/1

##### Delete all characters :
### route : DELETE "/characters"
## controller : "DeleteAllCharacters()"
DELETE {{baseURL}}/characters

##### Search a specific character :
### route : GET "/search"
## controller : "GetCharacterByParameter()"
### (first_name)
GET {{baseURL}}/search?type=first_name&value=Tony
### (last_name)
GET {{baseURL}}/search?type=last_name&value=Stark
### (alias)
GET {{baseURL}}/search?type=alias&value=Iron%20Man


##### Sort characters by his first_name, last_name or alias in ascending or descending order :
### route : GET "/sort"
## controller : "SortCharacters()"
### (last_name) (asc)
GET {{baseURL}}/sort?type=last_name&sort=asc
### (last_name) (desc)
GET {{baseURL}}/sort?type=last_name&sort=desc

### (first_name) (asc)
GET {{baseURL}}/sort?type=first_name&sort=asc
### (first_name) (desc)
GET {{baseURL}}/sort?type=first_name&sort=desc

### (alias) (asc)
GET {{baseURL}}/sort?type=alias&sort=asc
### (alias) (desc)
GET {{baseURL}}/sort?type=alias&sort=desc